import type { StrategyDefinition } from "../../../shared/types";

const NOT_PREDICTION_DISCLAIMER = "Não prevê o próximo sorteio nem altera a probabilidade de uma combinação individual.";

export const LOTOFACIL_RMS_V2: StrategyDefinition = {
  id: "lotofacil.rms_v2",
  version: "2.0.0",
  modality: "lotofacil",
  name: "RMS v2",
  shortDescription: "Carteira de 6 jogos com padrões A-B-C, exposição e sobreposição auditadas sobre os 20 concursos anteriores.",
  status: "active",
  evidence: "structural",
  ticketCount: { mode: "fixed", fixed: 6 },
  supportsBudget: false,
  supportsFixedNumbers: false,
  supportsExcludedNumbers: false,
  supportsUserSeed: false,
  supportsQualityPreset: false,
  requiresHistoricalDraws: true,
  requiresTargetContest: true,
  historyWindowSize: 20,
  optimizedMetrics: ["exposição 3-4 por dezena", "interseção 7-9 por par", "diversificação estrutural"],
  reportedMetrics: ["F11+", "F12+", "F13+", "F14+", "F15", "sobreposição", "baseline"],
  disclaimers: [
    NOT_PREDICTION_DISCLAIMER,
    "Não afirma que a RMS aumenta a chance de 15 acertos frente a outros 6 jogos distintos.",
    "O histórico define rotação/pools, não dezenas mais prováveis.",
  ],
};

export const LOTOFACIL_MAX_DIVERSIFICATION: StrategyDefinition = {
  id: "lotofacil.max_diversification",
  version: "1.0.0",
  modality: "lotofacil",
  name: "Diversificação de carteira",
  shortDescription: "Equilibra a exposição das 25 dezenas e reduz a sobreposição entre os jogos.",
  status: "active",
  evidence: "mathematical",
  ticketCount: { mode: "range", min: 1, max: 50 },
  supportsBudget: true,
  supportsFixedNumbers: true,
  supportsExcludedNumbers: true,
  supportsUserSeed: true,
  supportsQualityPreset: false,
  requiresHistoricalDraws: false,
  requiresTargetContest: false,
  optimizedMetrics: ["equilíbrio de exposição", "sobreposição média/máxima"],
  reportedMetrics: ["F11+", "F12+", "F13+", "F14+", "F15", "baseline"],
  disclaimers: [NOT_PREDICTION_DISCLAIMER],
};

export const LOTOFACIL_MAX_COVERAGE_11: StrategyDefinition = {
  id: "lotofacil.max_coverage_11",
  version: "1.0.0",
  modality: "lotofacil",
  name: "Otimizar cobertura 11+",
  shortDescription: "Busca heurística que maximiza diretamente a cobertura de resultados com 11 acertos ou mais.",
  status: "active",
  evidence: "structural",
  ticketCount: { mode: "range", min: 1, max: 50 },
  supportsBudget: true,
  supportsFixedNumbers: true,
  supportsExcludedNumbers: true,
  supportsUserSeed: true,
  supportsQualityPreset: true,
  requiresHistoricalDraws: false,
  requiresTargetContest: false,
  optimizedMetrics: ["cobertura 11+ (amostrada durante a busca)"],
  reportedMetrics: ["F11+", "F12+", "F13+", "F14+", "F15", "baseline"],
  disclaimers: [NOT_PREDICTION_DISCLAIMER, "Melhor solução encontrada pelo algoritmo, sem prova de ótimo global."],
};

export const LOTOFACIL_MAX_COVERAGE_12: StrategyDefinition = {
  id: "lotofacil.max_coverage_12",
  version: "1.0.0",
  modality: "lotofacil",
  name: "Otimizar cobertura 12+",
  shortDescription: "Busca heurística que maximiza diretamente a cobertura de resultados com 12 acertos ou mais.",
  status: "active",
  evidence: "structural",
  ticketCount: { mode: "range", min: 1, max: 50 },
  supportsBudget: true,
  supportsFixedNumbers: true,
  supportsExcludedNumbers: true,
  supportsUserSeed: true,
  supportsQualityPreset: true,
  requiresHistoricalDraws: false,
  requiresTargetContest: false,
  optimizedMetrics: ["cobertura 12+ (amostrada durante a busca)"],
  reportedMetrics: ["F11+", "F12+", "F13+", "F14+", "F15", "baseline"],
  disclaimers: [NOT_PREDICTION_DISCLAIMER, "Melhor solução encontrada pelo algoritmo, sem prova de ótimo global."],
};

export const LOTOFACIL_UNIFORM_RANDOM: StrategyDefinition = {
  id: "lotofacil.uniform_random",
  version: "1.0.0",
  modality: "lotofacil",
  name: "Aleatória distinta",
  shortDescription: "Jogos gerados de forma uniforme e distinta, sem filtros estruturais ocultos.",
  status: "active",
  evidence: "baseline",
  ticketCount: { mode: "range", min: 1, max: 50 },
  supportsBudget: true,
  supportsFixedNumbers: true,
  supportsExcludedNumbers: true,
  supportsUserSeed: true,
  supportsQualityPreset: false,
  requiresHistoricalDraws: false,
  requiresTargetContest: false,
  optimizedMetrics: [],
  reportedMetrics: ["F11+", "F12+", "F13+", "F14+", "F15", "baseline"],
  disclaimers: [NOT_PREDICTION_DISCLAIMER, "Não deve ser confundida com a baseline teórica de comparação."],
};

export const LOTOFACIL_STRATEGIES: StrategyDefinition[] = [
  LOTOFACIL_RMS_V2,
  LOTOFACIL_MAX_DIVERSIFICATION,
  LOTOFACIL_MAX_COVERAGE_11,
  LOTOFACIL_MAX_COVERAGE_12,
  LOTOFACIL_UNIFORM_RANDOM,
];
